export const periodicTable = [
  { atomicNumber: 1, symbol: "H", name: "Hydrogen", relativeAtomicMass: 1.008 },
  { atomicNumber: 2, symbol: "He", name: "Helium", relativeAtomicMass: 4.0026 },
  { atomicNumber: 3, symbol: "Li", name: "Lithium", relativeAtomicMass: 6.94 },
  { atomicNumber: 4, symbol: "Be", name: "Beryllium", relativeAtomicMass: 9.0122 },
  { atomicNumber: 5, symbol: "B", name: "Boron", relativeAtomicMass: 10.81 },
  { atomicNumber: 6, symbol: "C", name: "Carbon", relativeAtomicMass: 12.011 },
  { atomicNumber: 7, symbol: "N", name: "Nitrogen", relativeAtomicMass: 14.007 },
  { atomicNumber: 8, symbol: "O", name: "Oxygen", relativeAtomicMass: 15.999 },
  { atomicNumber: 9, symbol: "F", name: "Fluorine", relativeAtomicMass: 18.998 },
  { atomicNumber: 10, symbol: "Ne", name: "Neon", relativeAtomicMass: 20.180 },
  { atomicNumber: 11, symbol: "Na", name: "Sodium", relativeAtomicMass: 22.990 },
  { atomicNumber: 12, symbol: "Mg", name: "Magnesium", relativeAtomicMass: 24.305 },
  { atomicNumber: 13, symbol: "Al", name: "Aluminium", relativeAtomicMass: 26.982 },
  { atomicNumber: 14, symbol: "Si", name: "Silicon", relativeAtomicMass: 28.085 },
  { atomicNumber: 15, symbol: "P", name: "Phosphorus", relativeAtomicMass: 30.974 },
  { atomicNumber: 16, symbol: "S", name: "Sulfur", relativeAtomicMass: 32.06 },
  { atomicNumber: 17, symbol: "Cl", name: "Chlorine", relativeAtomicMass: 35.45 },
  { atomicNumber: 18, symbol: "Ar", name: "Argon", relativeAtomicMass: 39.948 },
  { atomicNumber: 19, symbol: "K", name: "Potassium", relativeAtomicMass: 39.0983 },
  { atomicNumber: 20, symbol: "Ca", name: "Calcium", relativeAtomicMass: 40.078 },
  { atomicNumber: 21, symbol: "Sc", name: "Scandium", relativeAtomicMass: 44.956 },
  { atomicNumber: 22, symbol: "Ti", name: "Titanium", relativeAtomicMass: 47.867 },
  { atomicNumber: 23, symbol: "V", name: "Vanadium", relativeAtomicMass: 50.942 },
  { atomicNumber: 24, symbol: "Cr", name: "Chromium", relativeAtomicMass: 51.996 },
  { atomicNumber: 25, symbol: "Mn", name: "Manganese", relativeAtomicMass: 54.938 },
  { atomicNumber: 26, symbol: "Fe", name: "Iron", relativeAtomicMass: 55.845 },
  { atomicNumber: 27, symbol: "Co", name: "Cobalt", relativeAtomicMass: 58.933 },
  { atomicNumber: 28, symbol: "Ni", name: "Nickel", relativeAtomicMass: 58.693 },
  { atomicNumber: 29, symbol: "Cu", name: "Copper", relativeAtomicMass: 63.546 },
  { atomicNumber: 30, symbol: "Zn", name: "Zinc", relativeAtomicMass: 65.38 },
  { atomicNumber: 31, symbol: "Ga", name: "Gallium", relativeAtomicMass: 69.723 },
  { atomicNumber: 32, symbol: "Ge", name: "Germanium", relativeAtomicMass: 72.630 },
  { atomicNumber: 33, symbol: "As", name: "Arsenic", relativeAtomicMass: 74.922 },
  { atomicNumber: 34, symbol: "Se", name: "Selenium", relativeAtomicMass: 78.971 },
  { atomicNumber: 35, symbol: "Br", name: "Bromine", relativeAtomicMass: 79.904 },
  { atomicNumber: 36, symbol: "Kr", name: "Krypton", relativeAtomicMass: 83.798 },
  { atomicNumber: 37, symbol: "Rb", name: "Rubidium", relativeAtomicMass: 85.468 },
  { atomicNumber: 38, symbol: "Sr", name: "Strontium", relativeAtomicMass: 87.62 },
  { atomicNumber: 39, symbol: "Y", name: "Yttrium", relativeAtomicMass: 88.906 },
  { atomicNumber: 40, symbol: "Zr", name: "Zirconium", relativeAtomicMass: 91.224 },
  { atomicNumber: 41, symbol: "Nb", name: "Niobium", relativeAtomicMass: 92.906 },
  { atomicNumber: 42, symbol: "Mo", name: "Molybdenum", relativeAtomicMass: 95.95 },
  { atomicNumber: 43, symbol: "Tc", name: "Technetium", relativeAtomicMass: 98 },
  { atomicNumber: 44, symbol: "Ru", name: "Ruthenium", relativeAtomicMass: 101.07 },
  { atomicNumber: 45, symbol: "Rh", name: "Rhodium", relativeAtomicMass: 102.91 },
  { atomicNumber: 46, symbol: "Pd", name: "Palladium", relativeAtomicMass: 106.42 },
  { atomicNumber: 47, symbol: "Ag", name: "Silver", relativeAtomicMass: 107.87 },
  { atomicNumber: 48, symbol: "Cd", name: "Cadmium", relativeAtomicMass: 112.41 },
  { atomicNumber: 49, symbol: "In", name: "Indium", relativeAtomicMass: 114.82 },
  { atomicNumber: 50, symbol: "Sn", name: "Tin", relativeAtomicMass: 118.71 },
  { atomicNumber: 51, symbol: "Sb", name: "Antimony", relativeAtomicMass: 121.76 },
  { atomicNumber: 52, symbol: "Te", name: "Tellurium", relativeAtomicMass: 127.60 },
  { atomicNumber: 53, symbol: "I", name: "Iodine", relativeAtomicMass: 126.90 },
  { atomicNumber: 54, symbol: "Xe", name: "Xenon", relativeAtomicMass: 131.29 },
  { atomicNumber: 55, symbol: "Cs", name: "Cesium", relativeAtomicMass: 132.91 },
  { atomicNumber: 56, symbol: "Ba", name: "Barium", relativeAtomicMass: 137.33 },
  { atomicNumber: 57, symbol: "La", name: "Lanthanum", relativeAtomicMass: 138.91 },
  { atomicNumber: 58, symbol: "Ce", name: "Cerium", relativeAtomicMass: 140.12 },
  { atomicNumber: 59, symbol: "Pr", name: "Praseodymium", relativeAtomicMass: 140.91 },
  { atomicNumber: 60, symbol: "Nd", name: "Neodymium", relativeAtomicMass: 144.24 },
  { atomicNumber: 61, symbol: "Pm", name: "Promethium", relativeAtomicMass: 145 },
  { atomicNumber: 62, symbol: "Sm", name: "Samarium", relativeAtomicMass: 150.36 },
  { atomicNumber: 63, symbol: "Eu", name: "Europium", relativeAtomicMass: 151.96 },
  { atomicNumber: 64, symbol: "Gd", name: "Gadolinium", relativeAtomicMass: 157.25 },
  { atomicNumber: 65, symbol: "Tb", name: "Terbium", relativeAtomicMass: 158.93 },
  { atomicNumber: 66, symbol: "Dy", name: "Dysprosium", relativeAtomicMass: 162.50 },
  { atomicNumber: 67, symbol: "Ho", name: "Holmium", relativeAtomicMass: 164.93 },
  { atomicNumber: 68, symbol: "Er", name: "Erbium", relativeAtomicMass: 167.26 },
  { atomicNumber: 69, symbol: "Tm", name: "Thulium", relativeAtomicMass: 168.93 },
  { atomicNumber: 70, symbol: "Yb", name: "Ytterbium", relativeAtomicMass: 173.05 },
  { atomicNumber: 71, symbol: "Lu", name: "Lutetium", relativeAtomicMass: 174.97 },
  { atomicNumber: 72, symbol: "Hf", name: "Hafnium", relativeAtomicMass: 178.49 },
  { atomicNumber: 73, symbol: "Ta", name: "Tantalum", relativeAtomicMass: 180.95 },
  { atomicNumber: 74, symbol: "W", name: "Tungsten", relativeAtomicMass: 183.84 },
  { atomicNumber: 75, symbol: "Re", name: "Rhenium", relativeAtomicMass: 186.21 },
  { atomicNumber: 76, symbol: "Os", name: "Osmium", relativeAtomicMass: 190.23 },
  { atomicNumber: 77, symbol: "Ir", name: "Iridium", relativeAtomicMass: 192.22 },
  { atomicNumber: 78, symbol: "Pt", name: "Platinum", relativeAtomicMass: 195.08 },
  { atomicNumber: 79, symbol: "Au", name: "Gold", relativeAtomicMass: 196.97 },
  { atomicNumber: 80, symbol: "Hg", name: "Mercury", relativeAtomicMass: 200.59 },
  { atomicNumber: 81, symbol: "Tl", name: "Thallium", relativeAtomicMass: 204.38 },
  { atomicNumber: 82, symbol: "Pb", name: "Lead", relativeAtomicMass: 207.2 },
  { atomicNumber: 83, symbol: "Bi", name: "Bismuth", relativeAtomicMass: 208.98 },
  { atomicNumber: 84, symbol: "Po", name: "Polonium", relativeAtomicMass: 209 },
  { atomicNumber: 85, symbol: "At", name: "Astatine", relativeAtomicMass: 210 },
  { atomicNumber: 86, symbol: "Rn", name: "Radon", relativeAtomicMass: 222 },
  { atomicNumber: 87, symbol: "Fr", name: "Francium", relativeAtomicMass: 223 },
  { atomicNumber: 88, symbol: "Ra", name: "Radium", relativeAtomicMass: 226 },
  { atomicNumber: 89, symbol: "Ac", name: "Actinium", relativeAtomicMass: 227 },
  { atomicNumber: 90, symbol: "Th", name: "Thorium", relativeAtomicMass: 232.04 },
  { atomicNumber: 91, symbol: "Pa", name: "Protactinium", relativeAtomicMass: 231.04 },
  { atomicNumber: 92, symbol: "U", name: "Uranium", relativeAtomicMass: 238.03 },
  { atomicNumber: 93, symbol: "Np", name: "Neptunium", relativeAtomicMass: 237 },
  { atomicNumber: 94, symbol: "Pu", name: "Plutonium", relativeAtomicMass: 244 },
  { atomicNumber: 95, symbol: "Am", name: "Americium", relativeAtomicMass: 243 },
  { atomicNumber: 96, symbol: "Cm", name: "Curium", relativeAtomicMass: 247 },
  { atomicNumber: 97, symbol: "Bk", name: "Berkelium", relativeAtomicMass: 247 },
  { atomicNumber: 98, symbol: "Cf", name: "Californium", relativeAtomicMass: 251 },
  { atomicNumber: 99, symbol: "Es", name: "Einsteinium", relativeAtomicMass: 252 },
  { atomicNumber: 100, symbol: "Fm", name: "Fermium", relativeAtomicMass: 257 },
  { atomicNumber: 101, symbol: "Md", name: "Mendelevium", relativeAtomicMass: 258 },
  { atomicNumber: 102, symbol: "No", name: "Nobelium", relativeAtomicMass: 259 },
  { atomicNumber: 103, symbol: "Lr", name: "Lawrencium", relativeAtomicMass: 266 },
  { atomicNumber: 104, symbol: "Rf", name: "Rutherfordium", relativeAtomicMass: 267 },
  { atomicNumber: 105, symbol: "Db", name: "Dubnium", relativeAtomicMass: 268 },
  { atomicNumber: 106, symbol: "Sg", name: "Seaborgium", relativeAtomicMass: 269 },
  { atomicNumber: 107, symbol: "Bh", name: "Bohrium", relativeAtomicMass: 270 },
  { atomicNumber: 108, symbol: "Hs", name: "Hassium", relativeAtomicMass: 270 },
  { atomicNumber: 109, symbol: "Mt", name: "Meitnerium", relativeAtomicMass: 278 },
  { atomicNumber: 110, symbol: "Ds", name: "Darmstadtium", relativeAtomicMass: 281 },
  { atomicNumber: 111, symbol: "Rg", name: "Roentgenium", relativeAtomicMass: 282 },
  { atomicNumber: 112, symbol: "Cn", name: "Copernicium", relativeAtomicMass: 285 },
  { atomicNumber: 113, symbol: "Nh", name: "Nihonium", relativeAtomicMass: 286 },
  { atomicNumber: 114, symbol: "Fl", name: "Flerovium", relativeAtomicMass: 289 },
  { atomicNumber: 115, symbol: "Mc", name: "Moscovium", relativeAtomicMass: 290 },
  { atomicNumber: 116, symbol: "Lv", name: "Livermorium", relativeAtomicMass: 293 },
  { atomicNumber: 117, symbol: "Ts", name: "Tennessine", relativeAtomicMass: 294 },
  { atomicNumber: 118, symbol: "Og", name: "Oganesson", relativeAtomicMass: 294 }
];


export const materials = [
  { formula: "H2", name: "Hydrogen Gas", composedOf: [1 , 1] },
  { formula: "H2O", name: "Water", composedOf: [1, 8] },
  { formula: "H2O2", name: "Hydrogen Peroxide", composedOf: [1, 8] },
  { formula: "CH4", name: "Methane", composedOf: [1, 6] },
  { formula: "He", name: "Helium Gas", composedOf: [2] },
  { formula: "Li2O", name: "Lithium Oxide", composedOf: [3, 8] },
  { formula: "LiF", name: "Lithium Fluoride", composedOf: [3, 9] },
  { formula: "BeO", name: "Beryllium Oxide", composedOf: [4, 8] },
  { formula: "BeF2", name: "Beryllium Fluoride", composedOf: [4, 9] },
  { formula: "B2O3", name: "Boron Trioxide", composedOf: [5, 8] },
  { formula: "CO2", name: "Carbon Dioxide", composedOf: [6, 8] },
  { formula: "CO", name: "Carbon Monoxide", composedOf: [6, 8] },
  { formula: "CH4", name: "Methane", composedOf: [6, 1] },
  { formula: "C2H6", name: "Ethane", composedOf: [6, 1] },
  { formula: "N2", name: "Nitrogen Gas", composedOf: [7] },
  { formula: "NH3", name: "Ammonia", composedOf: [7, 1] },
  { formula: "NO2", name: "Nitrogen Dioxide", composedOf: [7, 8] },
  { formula: "O2", name: "Oxygen Gas", composedOf: [8] },
  { formula: "O3", name: "Ozone", composedOf: [8] },
  { formula: "F2", name: "Fluorine Gas", composedOf: [9] },
  { formula: "HF", name: "Hydrogen Fluoride", composedOf: [1, 9] }
];
